name: Update README with Daily Quote

on:
  schedule:
    - cron: "0 6 * * *"  # Every day at 6 AM UTC
  workflow_dispatch:      # Allow manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Run Python Script
        run: python update_readme.py

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "✨ Daily quote update" || echo "No changes to commit"
          git push
